package firewall_test

import (
	"reflect"
	"strings"
	"testing"

	"github.com/YiLanTinYu/kylin-security-remediator/internal/firewall"
)

func TestBuildPlanAddsIndependentChainBeforeVendorChains(t *testing.T) {
	current := strings.Join([]string{
		"-P INPUT ACCEPT",
		"-N CEMS_COMMON_INPUT",
		"-N KSC_PUBLIC_INPUT",
		"-A INPUT -j CEMS_COMMON_INPUT",
		"-A INPUT -i eno1 -j KSC_PUBLIC_INPUT",
		"-A CEMS_COMMON_INPUT -p tcp --dport 3389 -j DROP",
		"-A CEMS_COMMON_INPUT -p tcp --dport 445 -j ACCEPT",
	}, "\n")

	plan, err := firewall.BuildPlan(current)
	if err != nil {
		t.Fatalf("BuildPlan() error = %v", err)
	}
	if len(plan) != 10 {
		t.Fatalf("commands = %d, want 10: %#v", len(plan), plan)
	}
	if !reflect.DeepEqual(plan[0].Args, []string{"-N", "SEC_REMEDIATOR_INPUT"}) {
		t.Fatalf("first command = %#v", plan[0].Args)
	}
	if !reflect.DeepEqual(plan[1].Args, []string{"-I", "INPUT", "1", "-j", "SEC_REMEDIATOR_INPUT"}) {
		t.Fatalf("jump command = %#v", plan[1].Args)
	}
	for _, command := range plan {
		joined := strings.Join(command.Args, " ")
		if strings.Contains(joined, "CEMS_") || strings.Contains(joined, "KSC_") {
			t.Fatalf("plan modifies vendor chain: %s", joined)
		}
	}
}

func TestBuildPlanIsEmptyWhenManagedRulesAreComplete(t *testing.T) {
	current := firewall.ExpectedSaveFixture()
	plan, err := firewall.BuildPlan(current)
	if err != nil {
		t.Fatalf("BuildPlan() error = %v", err)
	}
	if len(plan) != 0 {
		t.Fatalf("plan = %#v, want empty", plan)
	}
}

func TestBuildPlanRemovesLegacy136Rules(t *testing.T) {
	current := firewall.ExpectedSaveFixture() + "\n" + strings.Join([]string{
		"-A SEC_REMEDIATOR_INPUT -p tcp --dport 136 -m comment --comment SecurityRemediator -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p udp --dport 136 -m comment --comment SecurityRemediator -j DROP",
	}, "\n")
	plan, err := firewall.BuildPlan(current)
	if err != nil {
		t.Fatalf("BuildPlan() error = %v", err)
	}
	if len(plan) != 2 {
		t.Fatalf("plan = %#v, want two legacy deletions", plan)
	}
	for _, command := range plan {
		joined := strings.Join(command.Args, " ")
		if !strings.HasPrefix(joined, "-D SEC_REMEDIATOR_INPUT ") || !strings.Contains(joined, "--dport 136") {
			t.Fatalf("unexpected legacy cleanup command: %s", joined)
		}
	}
}

func TestBuildPlanRecognizesRulesAsIPTablesSaveActuallySerializesThem(t *testing.T) {
	lines := []string{"-P INPUT ACCEPT", "-N " + firewall.Chain, "-A INPUT -j " + firewall.Chain}
	for _, rule := range []string{
		"-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 22 -m comment --comment \"SecurityRemediator\" -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 135 -m comment --comment \"SecurityRemediator\" -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p udp -m udp --dport 137 -m comment --comment \"SecurityRemediator\" -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p udp -m udp --dport 138 -m comment --comment \"SecurityRemediator\" -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 139 -m comment --comment \"SecurityRemediator\" -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 445 -m comment --comment \"SecurityRemediator\" -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 3389 -m comment --comment \"SecurityRemediator\" -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p udp -m udp --dport 3389 -m comment --comment \"SecurityRemediator\" -j DROP",
	} {
		lines = append(lines, rule)
	}

	plan, err := firewall.BuildPlan(strings.Join(lines, "\n"))
	if err != nil {
		t.Fatalf("BuildPlan() error = %v", err)
	}
	if len(plan) != 0 {
		t.Fatalf("plan = %#v, want empty for real iptables-save form", plan)
	}
}

func TestBuildPlanRecognizesNFTablesSaveWithoutQuotedComment(t *testing.T) {
	current := `# Generated by iptables-save v1.8.10 (nf_tables)
*filter
:INPUT ACCEPT [81:23320]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:SEC_REMEDIATOR_INPUT - [0:0]
-A INPUT -j SEC_REMEDIATOR_INPUT
-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 22 -m comment --comment SecurityRemediator -j DROP
-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 135 -m comment --comment SecurityRemediator -j DROP
-A SEC_REMEDIATOR_INPUT -p udp -m udp --dport 137 -m comment --comment SecurityRemediator -j DROP
-A SEC_REMEDIATOR_INPUT -p udp -m udp --dport 138 -m comment --comment SecurityRemediator -j DROP
-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 139 -m comment --comment SecurityRemediator -j DROP
-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 445 -m comment --comment SecurityRemediator -j DROP
-A SEC_REMEDIATOR_INPUT -p tcp -m tcp --dport 3389 -m comment --comment SecurityRemediator -j DROP
-A SEC_REMEDIATOR_INPUT -p udp -m udp --dport 3389 -m comment --comment SecurityRemediator -j DROP
COMMIT
# Completed by iptables-save`

	plan, err := firewall.BuildPlan(current)
	if err != nil {
		t.Fatalf("BuildPlan() error = %v", err)
	}
	if len(plan) != 0 {
		t.Fatalf("plan = %#v, want empty for nftables save form", plan)
	}
}

func TestBuildPlanRemovesDuplicateManagedJumpAndRules(t *testing.T) {
	current := strings.Join([]string{
		"-N SEC_REMEDIATOR_INPUT",
		"-A INPUT -j CEMS_COMMON_INPUT",
		"-A INPUT -j SEC_REMEDIATOR_INPUT",
		"-A INPUT -j SEC_REMEDIATOR_INPUT",
		"-A SEC_REMEDIATOR_INPUT -p tcp --dport 22 -m comment --comment SecurityRemediator -j DROP",
		"-A SEC_REMEDIATOR_INPUT -p tcp --dport 22 -m comment --comment SecurityRemediator -j DROP",
	}, "\n")

	plan, err := firewall.BuildPlan(current)
	if err != nil {
		t.Fatalf("BuildPlan() error = %v", err)
	}
	joined := make([]string, 0, len(plan))
	for _, command := range plan {
		joined = append(joined, strings.Join(command.Args, " "))
	}
	for _, want := range []string{
		"-I INPUT 1 -j SEC_REMEDIATOR_INPUT",
		"-D INPUT 4",
		"-D INPUT 3",
		"-D SEC_REMEDIATOR_INPUT -p tcp --dport 22 -m comment --comment SecurityRemediator -j DROP",
	} {
		if !contains(joined, want) {
			t.Errorf("plan missing %q: %#v", want, joined)
		}
	}
}

func contains(items []string, expected string) bool {
	for _, item := range items {
		if item == expected {
			return true
		}
	}
	return false
}
